### ISSUE TITLE
add 3.x release ?

### ISSUE THREAD

**Issue by maboiteaspam** [slimphp/Slim-Skeleton#21]
Hi,

maybe i m missing something, I was expecting to install slim3, i got slim 2 after i run the composer generator.

**Comment by tuupola** [comment]
What is the command you ran?

**Comment by maboiteaspam** [comment]
```
php composer.phar create-project slim/slim-skeleton tomate
```

Not sure how it works, just noticed that there is no release with recent changes, see https://github.com/slimphp/Slim-Skeleton/releases

**Comment by akrabat** [comment]
Fixed. Thanks for letting us know.

**Comment by akrabat** [comment]
Reopening as packagist doesn't seem to have updated & I don't have time to investigate now.

**Comment by Estejin** [comment]
Still not fixed, I ran the command, and Slim 2.6 was installed

**Comment by Estejin** [comment]
change the created composer.json, then run update, but the directories are changed.

**Comment by rodneyo** [comment]
when I ran composer create-project slim/slim-skeleton [my-project]  the src directory in the skeleton app was not cloned.  I had to clone the github project then run composer install.  Is that the proper way to install the skeleton app or am I missing a step?

thanks for your help

**Comment by Estejin** [comment]
The correct way is:
1, run the command.
2, Change the composer.json with the new one, slim 3.0 is must.
3, run composer update

but, the index.php is old, have to update to Slim 3.0

**Comment by silentworks** [comment]
This is due to Packagist not being updated to the latest tag as yet, we will fix this soon.

**Comment by akrabat** [comment]
This has been really fixed now! https://packagist.org/packages/slim/slim-skeleton

**Comment by maboiteaspam** [comment]
:+1:  

Just for double confirmation,

```
composer create-project slim/slim-skeleton tomate
Installing slim/slim-skeleton (3.0.0)
  - Installing slim/slim-skeleton (3.0.0)
    Downloading: 100%

Created project in tomate
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing monolog/monolog (1.17.2)
    Loading from cache

  - Installing psr/http-message (1.0)
    Loading from cache

  - Installing slim/php-view (2.0.5)
    Downloading: 100%

  - Installing pimple/pimple (v3.0.2)
    Loading from cache

  - Installing nikic/fast-route (v0.6.0)
    Loading from cache

  - Installing container-interop/container-interop (1.1.0)
    Loading from cache

  - Installing slim/slim (3.0.0)
    Loading from cache

monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing raven/raven (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing videlalvaro/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
Generating autoload files
```
